remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

gem "github-pages", group: :jekyll_plugins

title: [Welcome to the Munich Cluster for Systems Neurology (SyNergy) GitHub page!]
