remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

gem "github-pages", group: :jekyll_plugins

description: |
  Using systems neurology as a new interdisciplinary approach, SyNergy researchers  
  investigate the shared disease mechanisms of neurovascular, neurodegenerative,  
  and neuro-immunological diseases, and on this basis develop novel diagnostic and  
  therapeutic approaches.  
  
  SyNergy has been funded as an Excellence Cluster by the  
  German Research Foundation (DFG) since 2012.
logo: /assets/img/SyNergy-Wortmarke-Claim-Druck-Weiss.png
